[project]
name = "sqlalchemy-ibmi"
version = "0.9.4"
description = "SQLAlchemy support for Db2 on IBM i"
readme = "README.md"
license = "Apache-2.0"
keywords = ["sqlalchemy", "database", "ibm", "ibmi", "db2"]
dynamic = ["classifiers"]
authors = [
    {name = "Korinne Adler", email = "kadler@us.ibm.com"},
    {name = "Naveen Ram", email = "naveen.ram@ibm.com"}
]
requires-python = ">=3.10"
dependencies = [
    "sqlalchemy (>=1.4.0,<3.0)",
    "pyodbc (>=5.0); python_version>='3.13'",
    "pyodbc (>=4.0); python_version<'3.13'",
]

[dependency-groups]
test = [
    "pytest >=7.2.1; python_version>='3.11'",
    "pytest >=6.2.5; python_version~='3.10'",
]
lint = [
    "flake8",
    "black ~=22.8.0",
]
dev = [
    { include-group = "test" },
    { include-group = "lint" },
    "bump-my-version",
]
docs = [
    "sphinx >1.0.0",
    "sphinx-rtd-theme >0.4.0",
]

[project.urls]
Homepage = "https://github.com/IBM/sqlalchemy-ibmi"
Repository = "https://github.com/IBM/sqlalchemy-ibmi"
Documentation = "https://sqlalchemy-ibmi.readthedocs.io"

[project.entry-points."sqlalchemy.dialects"]
ibmi = "sqlalchemy_ibmi.base:IBMiDb2Dialect"
"ibmi.pyodbc" = "sqlalchemy_ibmi.base:IBMiDb2Dialect"

[build-system]
requires = ["poetry-core (>=2.0.0,<3.0.0)"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
classifiers =[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Database :: Front-Ends",
]

packages = [
    {include = "sqlalchemy_ibmi"}
]

include = [
    { path = "test/*", format = "sdist" },
    { path = "contributing/*", format = "sdist" },
    { path = "docs/*", format = "sdist" },
    { path = "setup.cfg", format = "sdist" },
    { path = "CHANGES", format = "sdist" },
    { path = "LICENSE", format = "sdist" },
]

requires-poetry = ">=2.0.0,<3.0.0"

[tool.black]
line-length = 88
required-version = 22

[tool.bumpversion]
current_version = "0.9.4"
commit = true
tag = true
tag_name = "{new_version}"
message = "Bump version: {current_version} → {new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
serialize = [
	"{major}.{minor}.{patch}-{release}",
	"{major}.{minor}.{patch}",
]
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        -                             # dash separator for pre-release section
        (?P<release>[a-zA-Z-]+)       # pre-release label
    )?                                # pre-release section is optional
"""

[tool.bumpversion.parts.release]
values = ["dev", "rc", "final"]
optional_value = "final"

[[tool.bumpversion.files]]
filename = "sqlalchemy_ibmi/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
